/*
 * generated by Xtext
 */
package ee.xtext.haxe.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HaxeUiModule extends ee.xtext.haxe.ui.AbstractHaxeUiModule {
	public HaxeUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
