/*
* generated by Xtext
*/
package ee.xtext.haxe.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HaxeAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("ee/xtext/haxe/parser/antlr/internal/InternalHaxe.tokens");
	}
}
