/*
 * generated by Xtext
 */
package ee.xtext.haxe.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class HaxeExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return ee.xtext.haxe.ui.internal.HaxeActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return ee.xtext.haxe.ui.internal.HaxeActivator.getInstance().getInjector("ee.xtext.haxe.Haxe");
	}
	
}
