/*
 * generated by Xtext
 */
package ee.xtext.haxe;




/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HaxeRuntimeModule extends ee.xtext.haxe.AbstractHaxeRuntimeModule {

}
