/*
* generated by Xtext
*/
package ee.xtext.haxe.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class HaxeOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
